In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')
add_df = pd.read_csv('classified_json_files/classified_exercises.csv')

In [3]:
df.head()

,subject,year,topic,exam,exercise,exercise_type,statement
0,Física,2016,Física cuántica y nuclear,Junio,JUNIO. EJERCICIO 2. OPCIÓN B,no clasificado,a) Teoría de Einstein del efecto fotoeléctrico...
1,Física,2016,Física cuántica y nuclear,Junio,JUNIO. EJERCICIO 4. OPCIÓN A,no clasificado,El * Pb emite dos partículas beta y se transfo...
2,Física,2016,Física cuántica y nuclear,Reserva 2,RESERVA 2. EJERCICIO 4. OPCIÓN A,no clasificado,a) Calcule la energía liberada en el proceso p...
3,Física,2016,Física cuántica y nuclear,Reserva 3,RESERVA 3. EJERCICIO 2. OPCIÓN A,no clasificado,a) ¿Qué se entiende por dualidad onda-corpúscu...
4,Física,2016,Física cuántica y nuclear,Reserva 4,RESERVA 4. EJERCICIO 2. OPCIÓN A,no clasificado,a) Escriba la ley de desintegración radiactiva...

In [4]:
add_df

,subject,year,topic,exam,type
0,QUÍMICA,2020,EQUILIBRIO QUÍMICO,"Junio, Ejercicio B2",Principio de LeChatelier
1,QUÍMICA,2020,EQUILIBRIO QUÍMICO,"Junio, Ejercicio C1",Concentraciones
2,QUÍMICA,2020,EQUILIBRIO QUÍMICO,"Junio, Ejercicio C1","Kc, Kp"
3,QUÍMICA,2020,EQUILIBRIO QUÍMICO,"Reserva 1, Ejercicio C1",Concentraciones
4,QUÍMICA,2020,EQUILIBRIO QUÍMICO,"Reserva 1, Ejercicio C1","Kc, Kp"
...,...,...,...,...,...
70,QUIMICA,2025,EQUILIBRIO QUÍMICO,"Junio, Ejercicio 2B",Cinética
71,QUIMICA,2025,EQUILIBRIO QUÍMICO,"Junio, Ejercicio 3A",Equilibrio heterogéneo
72,QUIMICA,2025,EQUILIBRIO QUÍMICO,"Reserva 1, Ejercicio 2A",Principio de LeChatelier
73,QUIMICA,2025,EQUILIBRIO QUÍMICO,"Reserva 2, Ejercicio 2B",Cinética
74,QUIMICA,2025,EQUILIBRIO QUÍMICO,"Julio, Ejercicio 3A","Kc, Kp"

In [5]:
def form_exercise_string(row):
    # exam = [row['exam'].upper() ]
    exercise = [i.upper() for i in row['exam'].split(', ')]
    return '. '.join(exercise)

In [6]:
add_df['exercise'] = add_df.apply(form_exercise_string, axis = 1)

In [7]:
add_df['exam'] = add_df['exam'].apply(lambda x : x.split(', ')[0])

In [9]:
add_df.rename(columns = {'type' : 'exercise_type'}, inplace=True)

In [11]:
add_df['statement'] = None

In [14]:
# subject,year,topic,exam,exercise_number,statement,exercise_type
add_df = add_df[['subject', 'year', 'topic', 'exam', 'exercise', 'exercise_type', 'statement']]

In [15]:
add_df.head()

,subject,year,topic,exam,exercise,exercise_type,statement
0,QUÍMICA,2020,EQUILIBRIO QUÍMICO,Junio,JUNIO. EJERCICIO B2,Principio de LeChatelier,None
1,QUÍMICA,2020,EQUILIBRIO QUÍMICO,Junio,JUNIO. EJERCICIO C1,Concentraciones,None
2,QUÍMICA,2020,EQUILIBRIO QUÍMICO,Junio,JUNIO. EJERCICIO C1,"Kc, Kp",None
3,QUÍMICA,2020,EQUILIBRIO QUÍMICO,Reserva 1,RESERVA 1. EJERCICIO C1,Concentraciones,None
4,QUÍMICA,2020,EQUILIBRIO QUÍMICO,Reserva 1,RESERVA 1. EJERCICIO C1,"Kc, Kp",None

In [13]:
df.head()

,subject,year,topic,exam,exercise,exercise_type,statement
0,Física,2016,Física cuántica y nuclear,Junio,JUNIO. EJERCICIO 2. OPCIÓN B,no clasificado,a) Teoría de Einstein del efecto fotoeléctrico...
1,Física,2016,Física cuántica y nuclear,Junio,JUNIO. EJERCICIO 4. OPCIÓN A,no clasificado,El * Pb emite dos partículas beta y se transfo...
2,Física,2016,Física cuántica y nuclear,Reserva 2,RESERVA 2. EJERCICIO 4. OPCIÓN A,no clasificado,a) Calcule la energía liberada en el proceso p...
3,Física,2016,Física cuántica y nuclear,Reserva 3,RESERVA 3. EJERCICIO 2. OPCIÓN A,no clasificado,a) ¿Qué se entiende por dualidad onda-corpúscu...
4,Física,2016,Física cuántica y nuclear,Reserva 4,RESERVA 4. EJERCICIO 2. OPCIÓN A,no clasificado,a) Escriba la ley de desintegración radiactiva...

In [16]:
df = pd.concat([df, add_df])

In [17]:
df.to_csv('data.csv', index = False)