In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data.csv')
add_df = pd.read_csv('classified_json_files/classified_exercises.csv')

In [4]:
df.head(2)

,subject,year,topic,exam,exercise,exercise_type,statement
0,Física,2016,Física cuántica y nuclear,Junio,JUNIO. EJERCICIO 2. OPCIÓN B,no clasificado,a) Teoría de Einstein del efecto fotoeléctrico...
1,Física,2016,Física cuántica y nuclear,Junio,JUNIO. EJERCICIO 4. OPCIÓN A,no clasificado,El * Pb emite dos partículas beta y se transfo...

In [5]:
add_df.head(2)

,subject,year,topic,exam,type
0,QUÍMICA,2020,EQUILIBRIO QUÍMICO,"Junio, Ejercicio B2",Principio de LeChatelier
1,QUÍMICA,2020,EQUILIBRIO QUÍMICO,"Junio, Ejercicio C1",Concentraciones

Function to create the exercise string from `exam` column values.

In [6]:
def form_exercise_string(row):
    # exam = [row['exam'].upper() ]
    exercise = [i.upper() for i in row['exam'].split(', ')]
    return '. '.join(exercise)

In [7]:
add_df['exercise'] = add_df.apply(form_exercise_string, axis = 1)

Extract exam from `exercise` string

In [8]:
add_df['exam'] = add_df['exam'].apply(lambda x : x.split(', ')[0])

Rename `type` to `exercise_type`

In [9]:
add_df.rename(columns = {'type' : 'exercise_type'}, inplace=True)

Add `statement` column

In [10]:
add_df['statement'] = None

Reaarrange the columns to match the columns in the base dataframe

In [11]:
# subject,year,topic,exam,exercise_number,statement,exercise_type
add_df = add_df[['subject', 'year', 'topic', 'exam', 'exercise', 'exercise_type', 'statement']]

Check if column structure matches the base dataframe

In [12]:
add_df.head(2)

,subject,year,topic,exam,exercise,exercise_type,statement
0,QUÍMICA,2020,EQUILIBRIO QUÍMICO,Junio,JUNIO. EJERCICIO B2,Principio de LeChatelier,None
1,QUÍMICA,2020,EQUILIBRIO QUÍMICO,Junio,JUNIO. EJERCICIO C1,Concentraciones,None

In [13]:
df.head(2)

,subject,year,topic,exam,exercise,exercise_type,statement
0,Física,2016,Física cuántica y nuclear,Junio,JUNIO. EJERCICIO 2. OPCIÓN B,no clasificado,a) Teoría de Einstein del efecto fotoeléctrico...
1,Física,2016,Física cuántica y nuclear,Junio,JUNIO. EJERCICIO 4. OPCIÓN A,no clasificado,El * Pb emite dos partículas beta y se transfo...

Merge dataframes

In [14]:
df = pd.concat([df, add_df])

Remove duplicates

In [15]:
df = df.drop_duplicates()

Clean `Química` subject name

In [16]:
df.loc[df.subject.isin(['QUÍMICA', 'QUIMICA', 'Química']), 'subject'] = 'Química'

Export the merged dataframe to `data.csv`

In [17]:
df.to_csv('data.csv', index = False)